version: '3.8'

services:
  postgres-db:
    image: postgres:15
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  springboot-app:
    image: user/springboot-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    env_file:
      - env/.env
    build: .
volumes:
  postgres_data:
